CREATE TABLE Roles (
	RoleId INT IDENTITY(1,1) PRIMARY KEY,
	RoleName NVARCHAR(20) UNIQUE NOT NULL,

	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	IsDeleted BIT NOT NULL DEFAULT 0,
	UpdateAt DATETIME NULL,
	IsActive BIT NOT NULL DEFAULT 1,

)

GO

CREATE OR ALTER PROCEDURE SP_Role_Insert
@RoleName NVARCHAR(20)
AS
BEGIN
	INSERT INTO Roles(RoleName) VALUES(LOWER(@RoleName))
END

GO

CREATE OR ALTER PROCEDURE SP_Roles_GetAll
AS
BEGIN
	SELECT * FROM Roles WHERE IsDeleted=0
END
GO
